# Generated by Django 3.2.9 on 2021-11-17 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='gallery',
        ),
    ]
