# Generated by Django 3.2.9 on 2021-11-17 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.post'),
            preserve_default=False,
        ),
    ]
